### ISSUE TITLE
Code does not work if some parameters are not trainable.

### ISSUE THREAD

**Issue by GBATZOLIS** [fadel/pytorch_ema#9]
The code does not work if some of the parameters are not trainable. It only works if all the parameters are trainable.

**Comment by GiangHLe** [comment]
Can you give me an example that shows not trainable parameter needs to compute the exponential moving average?

**Comment by Linux-cpp-lisp** [comment]
Hi @GBATZOLIS , thanks for the bug report.

I believe the issue is that when you initialize `ExponentialMovingAverage` it silently ignores parameters that are not trainable; when you later pass `model.parameters()` to some method it contains more parameters (the non-trainable ones) than the EMA object has state for. Does this align with the error messages you see?

While we are considering if this current behavior makes sense, I _think_ this should be an easy workaround: just pass `[p for p in model.parameters() if p.requires_grad]` instead of `model.parameters()`.

**Comment by Linux-cpp-lisp** [comment]
I believe I have addressed this in https://github.com/fadel/pytorch_ema/commit/30a1306f2e5dc6aa91b4b64c2a3acd1bb3b0d7b6.

In that commit, the code will no longer check whether a parameter is trainable, and will process *all* parameters passed to it. This means that if you don't want to do EMA on some parameters, you *must not pass them to the EMA object*.

**Comment by GBATZOLIS** [comment]
Good solution.
